GROQ_API_KEY="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"
['google_service_account']
type = "service_account"
project_id = "geminiapidocsearch"
private_key_id = "fe4cf43e90fefa4154579b82bd15be0b2b58fc03"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDjYB2fJtfRTUiG
e3t4Y12ou1vGFa48QBaVGmaQNpeC2mIBwAPuR5uncCaXNC3SXfyPW8ikHZ5cGa/F
jnv+NETrDDCREOZC16QB1N2AbosHQ7L+Ss+zudr/R6sRK82Iy9b9IVHnPSYpORz4
yHpuoklv7XdgeDdupbYvV3lZt5NaBuFstVFi09rg01Z9kI1Q0riKuv0nnsS2JjZe
HIYoTJCyYoQAIXHO+tJ7K02DxWAoQdITmOA+duewpvmqEXYutz8CAiJJjpIpYu3Z
tk/0VOOMVz6TrFfZ6YyIu5nhFmuglFB8MwQm1cAWb9LF3bdXfxDgBBL9voDQZhR1
tq2rUXQNAgMBAAECggEALYG0nAA9rHWvwL6hCQi2G4mYBg6bxxI6ks/sXAuZCkbj
257PCpcJV5sSFiwKybIm1JhVkUceRSec7sikF03lxzcy1y3PL+yRtg4g4M3/BE6v
2cYmSL23T2VMHw0pvymw1wuepU2vQAveuQoCuva/BOg9frDAw2PmERaMQoEDvD4I
tivFkfTp8QnRP1M7Ft7I4/2iiuVD26sYBDbhhOTypcJzCrzKcS0LtOHlndcC93gB
h4ZyKKvQ5A+IEllt2wB5WHL1u6OK/VD93nDlytSQP2oH8IC3xcxF5xT2BgrjQFeE
h+qKTi2xVfI0+oM7UKOn74/iZ/bmH5KkNDAmyYxUEQKBgQD0MoQlX+miEBCSZC4K
Qjx971xY4P1Bf9QUtDvVarQN9u8DtBJEKrIjoQRuizuNsADgQMbhxwaslbVg9OY8
fGXvNQs12WpwT9Ey7pg95vlFg8JtNPdy2n0uKaqxmD8eWlJ+hI+9JwFdNTpI4xzk
bAwWHjcxP4m+cuzJiJi54N2RiQKBgQDuXXXZVMpuGVJKmb3OZuVRb9hrfUsLpl8E
5g/FhXHgCncqH8cO2AtXlNzwZ6/+APHAt5WQhdK+ZrY41K3/az+SyS6VavQx6lrG
eVrm1hFhoKpMsyLFqYk9n71Xb6Iy82QG49sDxHKujkTj+UqtvdjoXgzmRiOLDal3
SukjgcmBZQKBgQC2Iqt/eN84WkUR+xh/3FFkGNDHFeCvJtmXK6rpDjIHrGMvXvK0
1yeQ/XrhvIWJs3mjyYzNP3YR6YOkMmU7PgmFdgnLe0MxS8cb9uukWA8aMyEj9PqP
NrlhYgCHf6esSu/2n4baLSqOS7ISRRr6oEAPiy/dUqe5XdyQoIpRMY/xCQKBgGA5
KlHJgM5hOm8TESQ5NWlilSMPOTRCvSjlFojODeI7V0+R9HFxlWKNnYMO2GTZTL5X
XfExlJl4LSdT88mgKdG/lSaMPnfH+00TwDZfRDT8/sJnrinM/rH5wh2B2yBmUILX
iJpEu2br17OP9y2b7ewfy2VJ+x8vLLITc3n58rZhAoGARCpEKh/5LKdC4qy3ziwT
6y6ntjRFOBZkzYbKlJFlSzBTLzY/IjJ4PsFKARfuNGZPZWUZ67Ez8iWD3+NM+m/F
1rxCpCRXanbTzMuk+wyQfwLLRTFid8jZBE9Hl3w+npNv9HDAWBYddmG5NupH1FYR
C48mae+9px3Y4IjadbPUHis=
-----END PRIVATE KEY-----"""
client_email = "pragyanai-sheets-projectdemo@geminiapidocsearch.iam.gserviceaccount.com"
client_id = "113909866268628600239"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/pragyanai-sheets-projectdemo%40geminiapidocsearch.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
